package org.rascalmpl.values;

//This code was generated by Rascal API gen
import org.rascalmpl.interpreter.types.RascalTypeFactory;
import org.eclipse.imp.pdb.facts.type.Type;
import org.eclipse.imp.pdb.facts.type.TypeFactory;
import org.eclipse.imp.pdb.facts.type.TypeStore;
import org.eclipse.imp.pdb.facts.*;

public class Message {
public static TypeStore typestore = new TypeStore(
 org.rascalmpl.values.errors.Factory.getStore(), 
 org.rascalmpl.values.locations.Factory.getStore());

private static TypeFactory tf = TypeFactory.getInstance();
private static RascalTypeFactory rtf = RascalTypeFactory.getInstance();


public static final Type Message = tf.abstractDataType(typestore, "Message");

 public static final Type Message_error 
   = tf.constructor(typestore,Message,"error",tf.stringType(),"msg",tf.sourceLocationType(),"at");
 public static final Type Message_warning 
   = tf.constructor(typestore,Message,"warning",tf.stringType(),"msg",tf.sourceLocationType(),"at");
 public static final Type Message_info 
   = tf.constructor(typestore,Message,"info",tf.stringType(),"msg",tf.sourceLocationType(),"at");
             


public static String Message_error_msg(IConstructor c){
 return ((IString)c.get(0)).getValue();
} 
public static ISourceLocation Message_error_at(IConstructor c){
 return (ISourceLocation)c.get(1);
} 
public static String Message_warning_msg(IConstructor c){
 return ((IString)c.get(0)).getValue();
} 
public static ISourceLocation Message_warning_at(IConstructor c){
 return (ISourceLocation)c.get(1);
} 
public static String Message_info_msg(IConstructor c){
 return ((IString)c.get(0)).getValue();
} 
public static ISourceLocation Message_info_at(IConstructor c){
 return (ISourceLocation)c.get(1);
} 

private static final class InstanceHolder {
 public final static Message factory = new Message();
}
 
public static Message getInstance() {
 return InstanceHolder.factory;
}


public static TypeStore getStore() {
 return typestore;
}
}